name: Infra

trigger:
- main
- features/*

# =========================================================
# DEFAULT AGENT POOL
# =========================================================
pool:
  name: InfraPool

variables:
  workingDir: '$(System.DefaultWorkingDirectory)/environment/dev'

stages:

# =========================================================
# PRE-COMMIT STAGE
# =========================================================
- stage: PreCommit
  displayName: Pre Commit

  jobs:
  - job: Terraform_PreCheck
    displayName: Terraform Init Validate

    steps:

    - checkout: self

    # -----------------------------------------------------
    # Restore Terraform Cache
    # -----------------------------------------------------
    - task: Cache@2
      displayName: Restore Terraform Cache
      inputs:
        key: 'terraform | "$(Agent.OS)" | environment/dev/.terraform.lock.hcl'
        restoreKeys: |
          terraform | "$(Agent.OS)"
        path: '$(System.DefaultWorkingDirectory)/environment/dev/.terraform'

    # -----------------------------------------------------
    # Terraform Init Template
    # -----------------------------------------------------
    - template: templates/terraform-init.yml
      parameters:
        workingDir: '$(workingDir)'

    # -----------------------------------------------------
    # Terraform Validate Template
    # -----------------------------------------------------
    - template: templates/terraform-validate.yml
      parameters:
        workingDir: '$(workingDir)'

    # -----------------------------------------------------
    # Terraform Format
    # -----------------------------------------------------
    - task: TerraformTaskV4@4
      displayName: Terraform Fmt
      inputs:
              workingDir: '$(workingDir)'
