trigger:
- main

pool:
  name: InfraPool

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
  serviceConnection: 'Service-connection-007'
  backendStorage: 'storagebackend007'
  backendContainer: 'tfstate'
  backendKey: 'dev.tfstate'

stages:

# =====================================================
# PRECHECK
# =====================================================
- stage: Precheck

  jobs:
  - job: Validate

    steps:

    - checkout: self

    # Cache
    - template: templates/terraform-cache.yml
      parameters:
        workingDirectory: $(workingDirectory)

    # Init
    - template: templates/terraform-init.yml
      parameters:
        workingDirectory: $(workingDirectory)
        serviceConnection: $(serviceConnection)
        backendStorage: $(backendStorage)
        backendContainer: $(backendContainer)
        backendKey: $(backendKey)

    # Validate
    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(workingDirectory)

# =====================================================
# PLAN
# =====================================================
- stage: Plan

  jobs:

  - template: templates/terraform-plan.yml
    parameters:
      workingDirectory: $(workingDirectory)
      serviceConnection: $(serviceConnection)

# =====================================================
# DEPLOY
# =====================================================
- stage: Deploy

  jobs:

  - template: templates/terraform-apply.yml
    parameters:
      workingDirectory: $(workingDirectory)
      serviceConnection: $(serviceConnection)